// Generated by sparkling autolink
import Foundation
import Lynx
import Sparkling
import SparklingMethod

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "com.sparkling.playground"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-debug-tool", iosModuleName: "DebugTool", className: "SparklingDebugTool"),
    SparklingAutolinkModule(name: "sparkling-media", iosModuleName: "", className: ""),
    SparklingAutolinkModule(name: "sparkling-storage", iosModuleName: "SPKStorage", className: "StorageMethod"),
    SparklingAutolinkModule(name: "sparkling-navigation", iosModuleName: "Router", className: "RouterMethod")
]

enum SparklingAutolink {
    private static var registered = false

    static func register() {
        guard !registered else { return }
        registered = true
        // No native extensions discovered.
    }
}
