// Generated by sparkling autolink
import Foundation
import Lynx
import Sparkling
import SparklingMethod

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "com.sparkling.app.SparklingGo"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-navigation", iosModuleName: "Router", className: "RouterMethod")
]

enum SparklingAutolink {
    private static var registered = false

    static func register() {
        guard !registered else { return }
        registered = true
        // No native extensions discovered.
    }
}
